print("\t Hello, world! \t\t\n")
print("\t Hello, world! \t\t\n".lstrip())
print("\t Hello, world! \t\t\n".rstrip())
print("Hello, world! \t\t\n".strip())
print("Hello, world! \t\t\n".strip().lower().capitalize())
print("Hello, world! \t\t\n".strip().upper())
print("Hello, world! \t\t\n".strip().upper().islower())
print("Hello, world! \t\t\n".strip().upper().isupper())
print("Hello, world! \t\t\n".strip().upper().isdigit())
print("Hello, world! \t\t\n".strip().upper().isalpha())